name: mediashin
description: "Windows Graphics User Interface for basic video tools."
publish_to: 'none'
version: 1.2.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.4.0
  window_manager: ^0.4.2
  go_router: ^14.2.7
  file_picker: ^8.1.2
  process_run: ^1.2.0+3
  path: ^1.9.0
  desktop_drop: ^0.5.0
  mime: ^2.0.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-VariableFont_wdth,wght.ttf
  assets:
    - assets/images/mediashin-logo.png